languageCode = "en"
languageName = "English"
displayName = "EN"
isoCode = "en"
weight = 1
rtl = false

title = "TechOps_"
description = "Revolutionizing Infrastructure Operations through Automated Solutions."
copyright = "&copy; 2023 TechOps株式会社"

dateFormat = "2006-01-02"

[params]
  mainSections = ["samples"]

[author]
  name = "Congo"
  image = "img/author.jpg"
  headline = "Not your ordinary theme!"
  bio = "This is an example author bio, and although there's a stock photo of a dog here, this article was actually created by a human. :dog:"
  links = [
    { twitter = "https://twitter.com/" },
    { facebook = "https://facebook.com/" },
    { linkedin = "https://linkedin.com/" },
    { youtube = "https://youtube.com/" },
  ]
